config/routes.rb
Rails.application.routes.draw do
  resources:articles do
    resources :comments ,only:[:create,:destroy,:edit,:update]
  end
    
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments, :dependent => :destroy
    validates :title, presence: true
    validates :title, length: {maximum: 20}
    validates :text, presence: true    
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :title, presence: true
  validates :text, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:show, :edit,:update,:destroy]
    
    def index
        @articles=Article.all
    end
    
    def show

    end
    def new
        @article=Article.new
    end
    
    def create
        @article=Article.new(article_params)
        if @article.save
            redirect_to articles_path
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @article.update(article_params)
            redirect_to articles_path
        else 
            render 'edit'
        end
    end
    
    def destroy
        @article.destroy
        redirect_to articles_path
    end
    
    private
    
    def article_params
        params[:article].permit(:title,:text)
    end
    
    def set_article
        @article=Article.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
#        before_action :set_comment, only: [:edit,:update,:destroy]
    
    def create
        @article=Article.find(params[:article_id])
        @comment=@article.comments.create(comment_params)
        redirect_to article_path(@article)
    end
    
    def edit
        @article=Article.find(params[:article_id])
        @comment=Comment.find(params[:id])
    end

    def update
        @article=Article.find(params[:article_id])
        @comment=Comment.find(params[:id])
        if @comment.update(comment_params)
            redirect_to article_path(@comment.article_id)
        else 
            redirect_to edit_article_comment_path(@comment.article_id,@comment)
        end
    end

    def destroy
        @comment=Comment.find(params[:id])
        @comment.destroy
        redirect_to article_path(params[:article_id])
    end
    
    private
        def comment_params
            params[:comment].permit(:title,:text)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
   <ul>
      <% if @article.errors.any? %>
      <% @article.errors.full_messages.each do |message| %>
      <li><%=message %></li>
      <% end %>
      <% end %>
   </ul>

<p>
   <%= f.label :title %><br>
   <%= f.text_field :title %>
</p>
<p>
   <%=f.label :text %><br>
   <%=f.text_area :text ,:size => "50x30" %><br>
</p>

<p>
   <%= f.submit %> 
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>記事の編集</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>記事一覧</h1>
<ul>
    <% @articles.each do |article| %>
    <li>
        <%= link_to article.title,article_path(article.id) %>
        <%= link_to "Edit",edit_article_path(article.id) %>
        <%= link_to "delete",article_path(article.id), method: :delete,data:{confirm: "are you sure?"}
        %>
    </li>
    <% end %>
</ul>

<%= link_to "新しい記事を書く",new_article_path %>

app/views/articles/new.html.erb
<h1>記事の追加</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<ul>
    <%=@article.text %>
</ul>
<%= "コメント一覧" %><br>
<ul>
    <% @article.comments.each do |comment|%>
    <HR>
    <li>
        <%= "タイトル" %><br>
        <%= comment.title %><br>
        <%= "コメント" %><br>
        <%= comment.text %><br>
        <%= link_to "delete",article_comment_path(comment.article_id,comment.id), method: :delete,data:{confirm: "are you sure?"}%>
        <%= link_to "edit",edit_article_comment_path(comment.article_id,comment.id)%>
    </li>
    <% end %>
    <%= "コメントを残す" %><br>
    <%= form_for [@article,@comment=@article.comments.build] do |f| %>
    <p>
       <% if @comment.errors.any? %>
       <% @comment.errors.full_messages.each do |message| %>
       <%=message %><br>
       <% end %>
       <% end %>

        <%= f.label :title %><br>
        <%= f.text_field :title %><br>
        <%=f.label :text %><br>
        <%=f.text_area :text ,:size => "50x3" %><br><br>
        <%= f.submit %> 
    </p>
    <% end %>
</ul>


<%= link_to "back",articles_path %>

app/views/comments/_form.html.erb
   <%= form_for [@article,@comment] do |f| %>
      <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
      </p>
      <p>
      <%=f.label :text %><br>
      <%=f.text_area :text ,:size => "50x3" %><br>
         <% if @comment.errors.any? %>
            <% @comment.errors.full_messages.each do |message| %>
            <%=message %><br>
         <% end %>
   <% end %>
      </p>
   <p>
      <%= f.submit %> 
   </p>
   <% end %>

app/views/comments/edit.html.erb
<h1>コメントの編集</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>